### ISSUE TITLE
Ошибки алгоритма

### ISSUE THREAD

**Issue by mezhmal** [KirillKornienko/PassageOfTheLabyrinth#1]
@KirillKornienko проверьте пожалуйста ваше решение на различных лабиринтах.

Например, на лабиринте
```
                { '.','.','.','.','#','.'},
                { '.','#','.','.','#','.'},
                { '.','#','#','.','.','#'},
                { '#','.','.','.','#','.'},
                { '.','.','#','.','.','.'}
```
ваш алгоритм отвечает, что лабиринт проходим (и это правильно), но длину пути вычисляет как -1.

А на примере лабиринта
```
                { '.','.','.','.','.','.'},
                { '.','.','.','.','.','.'},
                { '.','.','.','.','.','.'},
                { '.','.','.','.','.','.'},
                { '.','.','.','.','.','.'}
```
входит в бесконечную рекурсию.

**Comment by KirillKornienko** [comment]
Первую ошибку я исправил, однако решение второй ошибки моим алгоритмом скорее невозможно (хотя быть может костыль какой-нибудь вставить?), поэтому я перепишу программу с использованием волнового алгоритма. Кстати, диагональный ход разрешается или только ортогональный?

**Comment by KirillKornienko** [comment]
Сделал ортогональный волновой алгоритм.

**Comment by mezhmal** [comment]
@KirillKornienko спасибо, получилось хорошо.
